import { ShieldAlert, ShieldCheck, ShieldQuestion } from "lucide-react";
import { formatDifference, formatPercent, riskStyle } from "../utils/risk";

const ICONS = {
  HIGH: ShieldAlert,
  MEDIUM: ShieldAlert,
  LOW: ShieldCheck,
};

export default function ProcurementNotice({ analysis }) {

  if (!analysis) return null;

  const style = riskStyle(analysis.risk);
  const Icon = ICONS[analysis.risk] || ShieldQuestion;
  const recommendation = analysis.recommendation || {};

  const rows = [
    ["Invoice Progress", formatPercent(analysis.invoice_progress), ""],
    ["Expected Progress", formatPercent(analysis.estimated_progress), ""],
    ["Difference", formatDifference(analysis.difference), "text-hazard-dark"],
    ["Risk Level", analysis.risk, style.text],
  ];

  return (

    <div className={`mt-8 rounded-2xl border-2 p-6 sm:p-8 shadow-sm ${style.panel}`}>

      <div className="flex flex-wrap items-center gap-4 mb-6">

        <Icon
          className={style.text}
          size={40}
        />

        <div className="flex-1 min-w-48">

          <h2 className="text-2xl font-bold text-sand-900">
            Procurement Recommendation
          </h2>

          <p className="text-sand-600 text-sm">
            Generated by Contract Sentinel
            {analysis.engine === "gemini" ? ` using ${analysis.model}` : " (rule-based engine)"}
          </p>

        </div>

        <span
          className={`rounded-xl border-2 px-5 py-2 text-lg font-extrabold tracking-wide ${style.badge}`}
        >
          {recommendation.decision}
        </span>

      </div>

      <div className="grid sm:grid-cols-2 gap-x-10 gap-y-3 text-sand-900">

        {rows.map(([label, value, color]) => (

          <div
            key={label}
            className="flex justify-between border-b border-dashed border-sand-300 pb-2"
          >

            <span className="text-sand-600">
              {label}
            </span>

            <span className={`font-bold ${color}`}>
              {value}
            </span>

          </div>

        ))}

      </div>

      <p className="mt-6 text-sand-800 leading-7">
        {recommendation.summary}
      </p>

    </div>

  );

}
