import { jsPDF } from "jspdf";

export function downloadReport(analysis) {
  const doc = new jsPDF();

  // Colors
  const primary = [14, 165, 233]; // cyan
  const dark = [40, 40, 40];
  const gray = [100, 100, 100];
  const red = [220, 38, 38];

  // Header
  doc.setFillColor(...primary);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("Contract Sentinel", 20, 18);

  doc.setFontSize(12);
  doc.text("AI Procurement Report", 20, 25);

  let y = 45;

  // Executive Summary
  doc.setTextColor(...dark);
  doc.setFontSize(17);
  doc.text("Executive Summary", 20, y);

  y += 8;

  doc.setDrawColor(...primary);
  doc.line(20, y, 190, y);

  y += 10;

  doc.setFontSize(12);

  doc.text("Invoice Progress", 20, y);
  doc.text(`${analysis.invoice_progress}%`, 170, y);

  y += 10;

  doc.text("AI Estimated Progress", 20, y);
  doc.text(`${analysis.estimated_progress}%`, 170, y);

  y += 10;

  doc.text("Difference", 20, y);
  doc.text(`${analysis.difference}%`, 170, y);

  y += 10;

  doc.setFont("helvetica", "bold");

  doc.text("Risk Level", 20, y);

  doc.setTextColor(...red);
  doc.text(analysis.risk, 170, y);

  doc.setTextColor(...dark);

  y += 18;

  // Findings
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);

  doc.text("AI Findings", 20, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  analysis.findings.forEach((finding) => {

    doc.circle(23, y - 1, 1.2, "F");

    doc.text(finding, 28, y, {
      maxWidth: 155,
    });

    y += 10;

  });

  y += 8;

  // Recommendation
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);

  doc.text("AI Procurement Recommendation", 20, y);

  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(
    "Invoice claims significantly higher work completion than estimated from project evidence.",
    20,
    y,
    {
      maxWidth: 170,
    }
  );

  y += 18;

  doc.setFont("helvetica", "bold");

  doc.text(
    "Recommendation: WITHHOLD PAYMENT",
    20,
    y
  );

  y += 10;

  doc.setFont("helvetica", "normal");

  doc.text(
    "Engineer verification is recommended before releasing milestone payment.",
    20,
    y,
    {
      maxWidth: 170,
    }
  );

  y += 25;

  // Footer
  doc.setDrawColor(180);
  doc.line(20, y, 190, y);

  y += 10;

  doc.setTextColor(...gray);
  doc.setFontSize(10);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    y
  );

  doc.text(
    "Generated by Contract Sentinel AI",
    20,
    y + 8
  );

  doc.save("Contract_Sentinel_Report.pdf");
}